# Generated by Django 2.2 on 2020-03-02 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Criminal', 'Criminal'), ('Drama', 'Drama'), ('Mystery', 'Mystery')], max_length=300),
        ),
    ]
